<?php
$newDolgozok =  array();
$dolgozok = array(
    array('d_nev' => 'Hajduné Pethő Zsuzsanna','a_id' => '1','t_id' => '1','p_id' => '34','b_datum' => '0'),
    array('d_nev' => 'Miskolczné Kőszegi Klára','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '0'),
    array('d_nev' => 'Nádori Péter','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Bozsik Enikő ','a_id' => '1','t_id' => '6','p_id' => '6','b_datum' => '0'),
    array('d_nev' => 'Gazsi Henrietta','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Bánfi Ernőné','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Balog Klára','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Márkus Anna','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Czibula Tibor','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Sallai Jánosné','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Szilágyi Panni','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Sponga Gáborné','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '0'),
    array('d_nev' => 'Zsabka Erzsébet Krisztina','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Schleicher Istvánné','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Lakatos Tamásné','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Petrikné Oláh Márta','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Szekeresné Király Gyöngyi ','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Bene Cintia M','a_id' => '4','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Gál Levente M','a_id' => '4','t_id' => '6','p_id' => '5','b_datum' => '0'),
    array('d_nev' => 'Gombkötő Csaba','a_id' => '1','t_id' => '6','p_id' => '6','b_datum' => '0'),
    array('d_nev' => 'Udvaros Edina','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '0'),
    array('d_nev' => 'Kovács Mónika','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Durai Tamás','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '0'),
    array('d_nev' => 'Babos Dániel','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '0'),
    array('d_nev' => 'Juhász László','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '0'),
    array('d_nev' => 'Hideghéti Anita','a_id' => '1','t_id' => '8','p_id' => '19','b_datum' => '0'),
    array('d_nev' => 'Mezsgyán Richárd','a_id' => '1','t_id' => '8','p_id' => '20','b_datum' => '0'),
    array('d_nev' => 'Somogyi László Junior','a_id' => '1','t_id' => '8','p_id' => '21','b_datum' => '0'),
    array('d_nev' => 'Opóczki Tamás','a_id' => '1','t_id' => '8','p_id' => '21','b_datum' => '0'),
    array('d_nev' => 'Parancs Dániel','a_id' => '1','t_id' => '8','p_id' => '21','b_datum' => '0'),
    array('d_nev' => 'Domonkos Gabriella Petra','a_id' => '1','t_id' => '8','p_id' => '22','b_datum' => '0'),
    array('d_nev' => 'Lakatos Helga','a_id' => '1','t_id' => '8','p_id' => '22','b_datum' => '0'),
    array('d_nev' => 'Pál Teréz','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Horváth Teréz','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Orosz Ella','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Nyitrai Rozália','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Bíró Nóra','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '0'),
    array('d_nev' => 'Vörös Kálmán','a_id' => '1','t_id' => '8','p_id' => '24','b_datum' => '0'),
    array('d_nev' => 'Rizmajer Richárd','a_id' => '1','t_id' => '8','p_id' => '24','b_datum' => '0'),
    array('d_nev' => 'Csürge Zoltán','a_id' => '1','t_id' => '8','p_id' => '24','b_datum' => '0'),
    array('d_nev' => 'Bólya István','a_id' => '1','t_id' => '9','p_id' => '28','b_datum' => '0'),
    array('d_nev' => 'Buzás Attila','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Bor Gábor Károly','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Fekete Sándor','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Szebényi Zsolt','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Fazakas Mihály','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Hajdu Dániel','a_id' => '1','t_id' => '8','p_id' => '21','b_datum' => '0'),
    array('d_nev' => 'Laczkó Sándor','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Rutterschmidt Zoltánné','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Horváth Sándor M','a_id' => '4','t_id' => '9','p_id' => '29','b_datum' => '0'),
    array('d_nev' => 'Farkas István Gáborné','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Balog Marianna','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Krizsán Károlyné','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Lánczos Ferencné','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Theil Viktória','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Jakab Éva','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Major Hajnalka','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Pölcz Tiborné Hajnalka','a_id' => '1','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Kovács Alíz M','a_id' => '4','t_id' => '9','p_id' => '30','b_datum' => '0'),
    array('d_nev' => 'Szluka Attiláné Erika','a_id' => '1','t_id' => '9','p_id' => '31','b_datum' => '0'),
    array('d_nev' => 'Nagy Péterné ','a_id' => '1','t_id' => '9','p_id' => '31','b_datum' => '0'),
    array('d_nev' => 'Molnár Nanda Mercedesz','a_id' => '1','t_id' => '9','p_id' => '32','b_datum' => '0'),
    array('d_nev' => 'Ódór Balázs','a_id' => '1','t_id' => '9','p_id' => '32','b_datum' => '0'),
    array('d_nev' => 'Tukacs Vanda','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '2020.09.11'),
    array('d_nev' => 'Rostné Butnaru Luminita','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '0'),
    array('d_nev' => 'Oláh Dániel','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '0'),
    array('d_nev' => 'Domonyi Sándor','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '0'),
    array('d_nev' => 'Polyák Mónika','a_id' => '7','t_id' => '1','p_id' => '34','b_datum' => '0'),
    array('d_nev' => 'Újvári Izabella','a_id' => '1','t_id' => '1','p_id' => '34','b_datum' => '0'),
    array('d_nev' => 'Ménich Adrienn Katalin','a_id' => '1','t_id' => '1','p_id' => '34','b_datum' => '0'),
    array('d_nev' => 'Belinszki Anita Julianna','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Márton Piroska','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Szabó Nikolett','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Kohán Szilvia','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Harmatiné Gazsik Éva','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Harazin Anett','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Juhász Judit','a_id' => '1','t_id' => '1','p_id' => '35','b_datum' => '0'),
    array('d_nev' => 'Volenszki Anett','a_id' => '1','t_id' => '1','p_id' => '36','b_datum' => '0'),
    array('d_nev' => 'Kocsis Brigitta','a_id' => '1','t_id' => '1','p_id' => '36','b_datum' => '0'),
    array('d_nev' => 'Herczéné Szapek Emese','a_id' => '1','t_id' => '1','p_id' => '37','b_datum' => '0'),
    array('d_nev' => 'Dinnyés Csaba','a_id' => '1','t_id' => '1','p_id' => '38','b_datum' => '0'),
    array('d_nev' => 'Bravik Erika Zsuzsanna','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Géró László Ferencné','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Fentor János Ádám','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Bednárik Erzsébet','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Fentor Dominik János','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Márton Viktória','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Peregovits Kálmánné','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Garajszki Mária','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Lajter Lászlóné','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Bakó János Pál M','a_id' => '4','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Varsányi Tamás','a_id' => '1','t_id' => '1','p_id' => '42','b_datum' => '0'),
    array('d_nev' => 'Surányi Zsolt','a_id' => '1','t_id' => '1','p_id' => '42','b_datum' => '0'),
    array('d_nev' => 'Koleff Sándor Miklós','a_id' => '1','t_id' => '1','p_id' => '42','b_datum' => '0'),
    array('d_nev' => 'Sziklási Lilla Ildikó','a_id' => '1','t_id' => '1','p_id' => '43','b_datum' => '0'),
    array('d_nev' => 'Urbán Krisztián','a_id' => '1','t_id' => '1','p_id' => '44','b_datum' => '0'),
    array('d_nev' => 'Rabné Szerényi Zita','a_id' => '1','t_id' => '1','p_id' => '44','b_datum' => '0'),
    array('d_nev' => 'Kanyik Bence','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Lengyel Bence','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Nagy Roland Zsolt','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Rózsahegyi Elemér','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Rukrigel Zsolt','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Kovács Árpád','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Wágenhoffer Róbert','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Podoba Dávid','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Csinos Attila','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Balogh István','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Kiss Gusztáv ','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '0'),
    array('d_nev' => 'Schneider Gábor','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Szabó József','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Józsa Dániel','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Dóczi István','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Czinege Gábor','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Szalai Xavér','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Szeibert Antal','a_id' => '1','t_id' => '3','p_id' => '46','b_datum' => '0'),
    array('d_nev' => 'Sztratyinszky Márk','a_id' => '3','t_id' => '3','p_id' => '47','b_datum' => '0'),
    array('d_nev' => 'Balogh Krisztián ','a_id' => '1','t_id' => '3','p_id' => '47','b_datum' => '0'),
    array('d_nev' => 'Lakatos István','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Garas Tamás','a_id' => '1','t_id' => '3','p_id' => '47','b_datum' => '0'),
    array('d_nev' => 'Wirt Gábor','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Márton Zoltán','a_id' => '7','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Csikós János Tamás','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Farkas László','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Péter Márton','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Litóczki József Krisztián','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Péter Zoltán ','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Csikós Tóbiás ','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Domján Imre ','a_id' => '1','t_id' => '3','p_id' => '48','b_datum' => '0'),
    array('d_nev' => 'Slezák József','a_id' => '1','t_id' => '6','p_id' => '49','b_datum' => '0'),
    array('d_nev' => 'Ónódi András','a_id' => '1','t_id' => '6','p_id' => '49','b_datum' => '0'),
    array('d_nev' => 'Kiss Róbert Ferencz','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Kovács Tamás','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Pekker István','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Jónás Miklós','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Halenkár Károly','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Schrick Ferenc György','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Szabó Péter','a_id' => '3','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Szente László ','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Lingurár György','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Lakatos László','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Mráz István','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Török Péter','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Turányi László','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Németh Izsák Krisztián ','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Nagy Richárd László M','a_id' => '4','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Balogh Antal András M','a_id' => '4','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Nagy István Zoltán M','a_id' => '4','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Balogh Bence M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Nagy Károly M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Ajtai Sándor M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Farkas András Imre M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Kolompár Ferenc M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Makula János Dávid M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Makula Norbert M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Makula Gusztáv M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Mező Attila M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Balogh Tivadar M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Kovács Kálmán M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Nagy Krisztián Zsolt M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Nagy József Levente M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Nagy András M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Mátyás Szebasztián M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Demeter Dávid','a_id' => '1','t_id' => '4','p_id' => '52','b_datum' => '0'),
    array('d_nev' => 'Bábel Benjámin','a_id' => '1','t_id' => '4','p_id' => '52','b_datum' => '0'),
    array('d_nev' => 'Halfinger József','a_id' => '1','t_id' => '4','p_id' => '52','b_datum' => '0'),
    array('d_nev' => 'Karlik László','a_id' => '1','t_id' => '4','p_id' => '52','b_datum' => '0'),
    array('d_nev' => 'Horváth Lajos','a_id' => '1','t_id' => '4','p_id' => '53','b_datum' => '0'),
    array('d_nev' => 'Györe Béla','a_id' => '1','t_id' => '4','p_id' => '53','b_datum' => '0'),
    array('d_nev' => 'Fekete János','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Kaszás Péter Sebestyén','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Szilveszter Imre','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Lánczos Zsolt','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Szennai István','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Sári Noémi Klára','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Ivanics Tamás ','a_id' => '1','t_id' => '4','p_id' => '54','b_datum' => '0'),
    array('d_nev' => 'Medve Pál','a_id' => '1','t_id' => '4','p_id' => '55','b_datum' => '0'),
    array('d_nev' => 'Avacz Tamás ','a_id' => '1','t_id' => '4','p_id' => '55','b_datum' => '0'),
    array('d_nev' => 'Györfi Imre','a_id' => '1','t_id' => '4','p_id' => '55','b_datum' => '0'),
    array('d_nev' => 'Farkas Tamásné','a_id' => '3','t_id' => '4','p_id' => '56','b_datum' => '0'),
    array('d_nev' => 'Botlik Angéla','a_id' => '1','t_id' => '4','p_id' => '56','b_datum' => '0'),
    array('d_nev' => 'Herpai Szilvia','a_id' => '1','t_id' => '4','p_id' => '56','b_datum' => '0'),
    array('d_nev' => 'Vellai Edit','a_id' => '1','t_id' => '4','p_id' => '57','b_datum' => '0'),
    array('d_nev' => 'Parászka Péter','a_id' => '1','t_id' => '4','p_id' => '58','b_datum' => '0'),
    array('d_nev' => 'Vitárizs Dávid','a_id' => '1','t_id' => '4','p_id' => '59','b_datum' => '0'),
    array('d_nev' => 'Petrik Amanda','a_id' => '1','t_id' => '10','p_id' => '60','b_datum' => '0'),
    array('d_nev' => 'Málinger Richárdné','a_id' => '1','t_id' => '10','p_id' => '60','b_datum' => '0'),
    array('d_nev' => 'Lánczosné Zelenák Regina','a_id' => '1','t_id' => '10','p_id' => '60','b_datum' => '0'),
    array('d_nev' => 'Klein Mónika','a_id' => '1','t_id' => '10','p_id' => '60','b_datum' => '0'),
    array('d_nev' => 'Lukácsi Judit','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Bálint Gabriella','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Böcsödi Barbara','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Tóthegyi Tímea','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Fabula Mária','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Balog Nikolett','a_id' => '1','t_id' => '10','p_id' => '61','b_datum' => '0'),
    array('d_nev' => 'Kondor Tiborné','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Nagyné Fogarasi Ágnes','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Szaller Brigitta','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Kabai Irén','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Farcas Claudia Tereza','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Lingvai Attiláné','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Haraszti Krisztina','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Tyukodi Mária','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Hideghétiné Garai Margit Aranka','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Somogyi Márta','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Józsa Lászlóné','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Sághi Anikó','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Karácsony Sándorné','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Üröginé Nagy Anna','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Polczer Gabriella','a_id' => '7','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Volter Mária','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Jugovitsné Pakó Katalin','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Horváthné Kátai Kinga','a_id' => '1','t_id' => '10','p_id' => '62','b_datum' => '0'),
    array('d_nev' => 'Mráz Mária','a_id' => '1','t_id' => '10','p_id' => '63','b_datum' => '0'),
    array('d_nev' => 'Sánta Beatrix','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Fehér Tibor','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Tulecz Márk','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Tóth Arnold','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Nagy Bence','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Szabó Richárd','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Ivanics Szabolcs ','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Kovács Krisztián János','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Rizmajer Krisztina','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Gazsó Csaba','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Pajor József','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Nagy László','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Kreisz Erik','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Göcs Tibor','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Bakonyiné Sipos Renáta','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Bobric Dominik','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Soós Zoltán','a_id' => '1','t_id' => '11','p_id' => '65','b_datum' => '0'),
    array('d_nev' => 'Saláta Ferenc Kálmán','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Mányoki Lajosné','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Kabai Diána Vivien','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Sándor Mercédesz ','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Szász Katalin	','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Kőbányai Ferenc József','a_id' => '1','t_id' => '12','p_id' => '68','b_datum' => '0'),
    array('d_nev' => 'Ogrin Antal','a_id' => '1','t_id' => '12','p_id' => '68','b_datum' => '0'),
    array('d_nev' => 'Romanek Károly','a_id' => '1','t_id' => '12','p_id' => '68','b_datum' => '0'),
    array('d_nev' => 'Takács László','a_id' => '1','t_id' => '12','p_id' => '68','b_datum' => '0'),
    array('d_nev' => 'Bán Ferenc ','a_id' => '1','t_id' => '12','p_id' => '68','b_datum' => '0'),
    array('d_nev' => 'Vas József','a_id' => '1','t_id' => '12','p_id' => '69','b_datum' => '0'),
    array('d_nev' => 'Fehér Zoltán','a_id' => '1','t_id' => '12','p_id' => '69','b_datum' => '0'),
    array('d_nev' => 'Ladány Szilvia T','a_id' => '4','t_id' => '6','p_id' => '6','b_datum' => '0'),
    array('d_nev' => 'Lakatos Fanni','a_id' => '1','t_id' => '6','p_id' => '6','b_datum' => '0'),
    array('d_nev' => 'Horváth Éva','a_id' => '1','t_id' => '25','p_id' => '84','b_datum' => '0'),
    array('d_nev' => 'Gáspár Zoltán','a_id' => '1','t_id' => '25','p_id' => '84','b_datum' => '0'),
    array('d_nev' => 'Langó Tiborné','a_id' => '1','t_id' => '25','p_id' => '84','b_datum' => '0'),
    array('d_nev' => 'Deli László','a_id' => '1','t_id' => '25','p_id' => '84','b_datum' => '0'),
    array('d_nev' => 'Lingurár Györgyné','a_id' => '1','t_id' => '25','p_id' => '84','b_datum' => '0'),
    array('d_nev' => 'Lakatos Gábor','a_id' => '1','t_id' => '8','p_id' => '25','b_datum' => '0'),
    array('d_nev' => 'Tóth László Mihályné','a_id' => '1','t_id' => '1','p_id' => '33','b_datum' => '0'),
    array('d_nev' => 'Kovácsné Pálesz Nikoletta','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Hajdu Norbert','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Szabó Dóra','a_id' => '1','t_id' => '1','p_id' => '39','b_datum' => '0'),
    array('d_nev' => 'Domján Imréné','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Finta Gyula Lászlóné','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '0'),
    array('d_nev' => 'Lakatos Tamás Tihamér','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Kolompár Endre M','a_id' => '4','t_id' => '3','p_id' => '50','b_datum' => '0'),
    array('d_nev' => 'Kovács Roland M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '0'),
    array('d_nev' => 'Mendi Sháron','a_id' => '1','t_id' => '10','p_id' => '60','b_datum' => '0'),
    array('d_nev' => 'Kovács Dániel','a_id' => '1','t_id' => '10','p_id' => '64','b_datum' => '0'),
    array('d_nev' => 'Kovács Károlyné','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Radics Bianka','a_id' => '1','t_id' => '11','p_id' => '66','b_datum' => '0'),
    array('d_nev' => 'Petrik Péter Pál ','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => ''),
    array('d_nev' => 'Szabóné Drjenovszky Anikó ','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => ''),
    array('d_nev' => 'Kónyáné Bilicska Andrea ','a_id' => '1','t_id' => '6','p_id' => '5','b_datum' => ''),
    array('d_nev' => 'Kovács Szintia ML','a_id' => '4','t_id' => '6','p_id' => '5','b_datum' => '2021.1.11'),
    array('d_nev' => 'Kovács Szilvia ML','a_id' => '4','t_id' => '6','p_id' => '5','b_datum' => '2021.1.11'),
    array('d_nev' => 'Rácz Jánosné ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Kovács Anikó Nikolett ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Lakatos Mariann ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Magos Barbara ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Duhaj Bernadett ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Sárközi Renáta T','a_id' => '4','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Tönköl Klaudia Bettina ','a_id' => '1','t_id' => '7','p_id' => '355','b_datum' => '2021.1.11'),
    array('d_nev' => 'Rostás Sándor Fabríció M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '2021.1.11'),
    array('d_nev' => 'Maksai Natália ','a_id' => '1','t_id' => '7','p_id' => '355','b_datum' => '2021.1.11'),
    array('d_nev' => 'Mráz Viktória ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Szmetana Tímea ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Pinczelné Juhász Katalin ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Krucsó Henrietta M','a_id' => '4','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Harsán Szilveszter Csilla M','a_id' => '4','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Ságiné Adóba Nikoletta ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.11'),
    array('d_nev' => 'Balogh Viktor ','a_id' => '1','t_id' => '7','p_id' => '357','b_datum' => '2021.1.11'),
    array('d_nev' => 'Rafael Ferenc ','a_id' => '3','t_id' => '7','p_id' => '357','b_datum' => '2021.1.11'),
    array('d_nev' => 'Marth Nikolett ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.11'),
    array('d_nev' => 'Cserháti Tamás Ferenc ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.11'),
    array('d_nev' => 'Gáspár Krisztián ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.11'),
    array('d_nev' => 'Gulyás Marianna ','a_id' => '3','t_id' => '7','p_id' => '358','b_datum' => '2021.1.11'),
    array('d_nev' => 'Simon Tibor ','a_id' => '1','t_id' => '7','p_id' => '359','b_datum' => '2021.1.11'),
    array('d_nev' => 'Takács Gábor ','a_id' => '1','t_id' => '7','p_id' => '359','b_datum' => '2021.1.11'),
    array('d_nev' => 'Radics János ','a_id' => '1','t_id' => '7','p_id' => '360','b_datum' => '2021.1.11'),
    array('d_nev' => 'Maris Martina ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Boros Adrienn T','a_id' => '4','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Kovácsné Zsolnai Éva ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Jobbágy Zoltánné ML','a_id' => '4','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Nagy Zsuzsanna T','a_id' => '4','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Majeczki Anna ','a_id' => '1','t_id' => '7','p_id' => '353','b_datum' => '2021.1.11'),
    array('d_nev' => 'Parragh Mónika ','a_id' => '1','t_id' => '7','p_id' => '354','b_datum' => '2021.1.11'),
    array('d_nev' => 'Boros Irén ','a_id' => '1','t_id' => '7','p_id' => '355','b_datum' => '2021.1.11'),
    array('d_nev' => 'Ajtai Erika M','a_id' => '4','t_id' => '7','p_id' => '355','b_datum' => '2021.1.12'),
    array('d_nev' => 'Tóth Kitti ','a_id' => '1','t_id' => '7','p_id' => '355','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szatmári Dóra ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.12'),
    array('d_nev' => 'Matuska Andrea Tímea ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.12'),
    array('d_nev' => 'Cotoi Hajnalka ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.12'),
    array('d_nev' => 'Mezei Katalin M','a_id' => '4','t_id' => '7','p_id' => '356','b_datum' => '2021.1.12'),
    array('d_nev' => 'Lajkó Marcell ','a_id' => '1','t_id' => '7','p_id' => '357','b_datum' => '2021.1.12'),
    array('d_nev' => 'Horváth Rajmund T','a_id' => '4','t_id' => '7','p_id' => '357','b_datum' => '2021.1.12'),
    array('d_nev' => 'Nagy Sándor Gábor T','a_id' => '4','t_id' => '7','p_id' => '357','b_datum' => '2021.1.12'),
    array('d_nev' => 'Varga Julianna ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.12'),
    array('d_nev' => 'Molnár Dániel József ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.12'),
    array('d_nev' => 'Czifra Mónika ','a_id' => '1','t_id' => '7','p_id' => '358','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szűcs Attila ','a_id' => '1','t_id' => '7','p_id' => '359','b_datum' => '2021.1.12'),
    array('d_nev' => 'Petrecz Arnold ','a_id' => '1','t_id' => '7','p_id' => '359','b_datum' => '2021.1.12'),
    array('d_nev' => 'Tóth Lászlóné ','a_id' => '1','t_id' => '7','p_id' => '361','b_datum' => '2021.1.12'),
    array('d_nev' => 'Varga Kinga Kitti M','a_id' => '4','t_id' => '7','p_id' => '361','b_datum' => '2021.1.12'),
    array('d_nev' => 'Marosánné Csörgő Andrea ','a_id' => '1','t_id' => '7','p_id' => '363','b_datum' => '2021.1.12'),
    array('d_nev' => 'Lakatos Éva ','a_id' => '1','t_id' => '7','p_id' => '363','b_datum' => '2021.1.12'),
    array('d_nev' => 'Nagy Melinda ','a_id' => '1','t_id' => '7','p_id' => '363','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kiss Andrea ','a_id' => '1','t_id' => '7','p_id' => '364','b_datum' => '2021.1.12'),
    array('d_nev' => 'Radics Georgina ','a_id' => '1','t_id' => '7','p_id' => '364','b_datum' => '2021.1.12'),
    array('d_nev' => 'Gáspár Karolina ','a_id' => '1','t_id' => '7','p_id' => '364','b_datum' => '2021.1.12'),
    array('d_nev' => 'Somogyi István Mihály ','a_id' => '1','t_id' => '7','p_id' => '365','b_datum' => '2021.1.12'),
    array('d_nev' => 'Sebestény Hanna T','a_id' => '4','t_id' => '7','p_id' => '366','b_datum' => '2021.1.12'),
    array('d_nev' => 'Budai Elemér M','a_id' => '4','t_id' => '7','p_id' => '367','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szmetana Anna ','a_id' => '1','t_id' => '7','p_id' => '369','b_datum' => '2021.1.12'),
    array('d_nev' => 'Zsótér Gabriella Andrea M','a_id' => '4','t_id' => '7','p_id' => '369','b_datum' => '2021.1.12'),
    array('d_nev' => 'Costrut Krisztina M','a_id' => '4','t_id' => '7','p_id' => '369','b_datum' => '2021.1.12'),
    array('d_nev' => 'Rózsás Nóra M','a_id' => '4','t_id' => '7','p_id' => '369','b_datum' => '2021.1.12'),
    array('d_nev' => 'Varga Krisztina ','a_id' => '1','t_id' => '7','p_id' => '371','b_datum' => '2021.1.12'),
    array('d_nev' => 'Csurai Norbertné ','a_id' => '1','t_id' => '7','p_id' => '372','b_datum' => '2021.1.12'),
    array('d_nev' => 'Románné Jurászki Edina ','a_id' => '1','t_id' => '7','p_id' => '372','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szakács Tiborné (Hamar Dóra) ','a_id' => '1','t_id' => '7','p_id' => '372','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bálint Roland ','a_id' => '1','t_id' => '7','p_id' => '373','b_datum' => '2021.1.12'),
    array('d_nev' => 'Lakatos Kálmán ','a_id' => '1','t_id' => '7','p_id' => '373','b_datum' => '2021.1.12'),
    array('d_nev' => 'Makula Attila M','a_id' => '4','t_id' => '7','p_id' => '373','b_datum' => '2021.1.12'),
    array('d_nev' => 'Baráth József M','a_id' => '4','t_id' => '7','p_id' => '373','b_datum' => '2021.1.12'),
    array('d_nev' => 'Krisztián Szabina ','a_id' => '1','t_id' => '7','p_id' => '374','b_datum' => '2021.1.12'),
    array('d_nev' => 'Felföldi Ádám ','a_id' => '1','t_id' => '7','p_id' => '374','b_datum' => '2021.1.12'),
    array('d_nev' => 'Somogyi Ilona Irén ','a_id' => '1','t_id' => '7','p_id' => '375','b_datum' => '2021.1.12'),
    array('d_nev' => 'Horváth István Máté ','a_id' => '1','t_id' => '7','p_id' => '375','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szabó Szintia ','a_id' => '1','t_id' => '7','p_id' => '377','b_datum' => '2021.1.12'),
    array('d_nev' => 'Béczi Alexandra ','a_id' => '1','t_id' => '7','p_id' => '377','b_datum' => '2021.1.12'),
    array('d_nev' => 'Rozmanit Gerda ','a_id' => '1','t_id' => '7','p_id' => '377','b_datum' => '2021.1.12'),
    array('d_nev' => 'Balog Viktória ','a_id' => '1','t_id' => '7','p_id' => '378','b_datum' => '2021.1.12'),
    array('d_nev' => 'Gyurgyikné Horváth Csilla ','a_id' => '1','t_id' => '7','p_id' => '379','b_datum' => '2021.1.12'),
    array('d_nev' => 'Gorócz Vanessza ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.12'),
    array('d_nev' => 'Simon Judit ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bravik Tímea ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.12'),
    array('d_nev' => 'Rácz Alex ','a_id' => '1','t_id' => '7','p_id' => '381','b_datum' => '2021.1.12'),
    array('d_nev' => 'Palenik Zoltán ','a_id' => '1','t_id' => '7','p_id' => '382','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szabó Szabocs Tamás ','a_id' => '1','t_id' => '7','p_id' => '382','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kohan József ','a_id' => '1','t_id' => '7','p_id' => '383','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szeles József ','a_id' => '1','t_id' => '7','p_id' => '383','b_datum' => '2021.1.12'),
    array('d_nev' => 'Horváth Dzsenifer ','a_id' => '1','t_id' => '7','p_id' => '379','b_datum' => '2021.1.12'),
    array('d_nev' => 'Takácsné Szűcs Irén Zsuzsanna ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.12'),
    array('d_nev' => 'Horváth Kálmánné ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.12'),
    array('d_nev' => 'Barát Jusztin Ivó M','a_id' => '4','t_id' => '7','p_id' => '381','b_datum' => '2021.1.12'),
    array('d_nev' => 'Tóth Ferenc ','a_id' => '1','t_id' => '7','p_id' => '383','b_datum' => '2021.1.12'),
    array('d_nev' => 'Mikola Lajos ','a_id' => '1','t_id' => '7','p_id' => '383','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bodó Richárd ','a_id' => '1','t_id' => '9','p_id' => '29','b_datum' => '2021.1.12'),
    array('d_nev' => 'Somogyi Heléna ML','a_id' => '4','t_id' => '9','p_id' => '30','b_datum' => '2021.1.12'),
    array('d_nev' => 'Semők Nóra ML','a_id' => '4','t_id' => '9','p_id' => '30','b_datum' => '2021.1.12'),
    array('d_nev' => 'Krizsán József ','a_id' => '8','t_id' => '9','p_id' => '32','b_datum' => '2021.1.12'),
    array('d_nev' => 'Nagyhajú Vivien T','a_id' => '4','t_id' => '8','p_id' => '18','b_datum' => '2021.1.12'),
    array('d_nev' => 'Németh Ferenc ','a_id' => '1','t_id' => '8','p_id' => '25','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bán Attila ','a_id' => '1','t_id' => '8','p_id' => '386','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szabó Norbert ','a_id' => '1','t_id' => '8','p_id' => '386','b_datum' => '2021.1.12'),
    array('d_nev' => 'Rehák Erzsébet Mária ','a_id' => '1','t_id' => '1','p_id' => '41','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kecskés János ','a_id' => '1','t_id' => '1','p_id' => '43','b_datum' => '2021.1.12'),
    array('d_nev' => 'Katona József ','a_id' => '1','t_id' => '1','p_id' => '44','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bakó György ','a_id' => '1','t_id' => '1','p_id' => '44','b_datum' => '2021.1.12'),
    array('d_nev' => 'Párizs Gábor ','a_id' => '1','t_id' => '3','p_id' => '26','b_datum' => '2021.1.12'),
    array('d_nev' => 'Halgass Sándor ','a_id' => '1','t_id' => '3','p_id' => '26','b_datum' => '2021.1.12'),
    array('d_nev' => 'Fejes Gergő ','a_id' => '1','t_id' => '3','p_id' => '26','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kovács Ádám ','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '2021.1.12'),
    array('d_nev' => 'Bennárik István ','a_id' => '1','t_id' => '3','p_id' => '45','b_datum' => '2021.1.12'),
    array('d_nev' => 'Mihályi András ML','a_id' => '4','t_id' => '3','p_id' => '50','b_datum' => '2021.1.12'),
    array('d_nev' => 'Horváth György ','a_id' => '1','t_id' => '3','p_id' => '50','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kovács Attila ','a_id' => '1','t_id' => '3','p_id' => '387','b_datum' => '2021.1.12'),
    array('d_nev' => 'Tusor Péter ','a_id' => '1','t_id' => '3','p_id' => '388','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szabó Péter M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '2021.1.12'),
    array('d_nev' => 'Tóth János ML','a_id' => '4','t_id' => '4','p_id' => '54','b_datum' => '2021.1.12'),
    array('d_nev' => 'Berényi Oszkár ML','a_id' => '4','t_id' => '4','p_id' => '55','b_datum' => '2021.1.12'),
    array('d_nev' => 'Szekeres Alex Tamás ','a_id' => '1','t_id' => '4','p_id' => '57','b_datum' => '2021.1.12'),
    array('d_nev' => 'Farkas Fanni Viktória M','a_id' => '6','t_id' => '7','p_id' => '361','b_datum' => '2021.1.12'),
    array('d_nev' => 'Kovács Ibolya M','a_id' => '4','t_id' => '6','p_id' => '5','b_datum' => '2021.01.11'),
    array('d_nev' => 'Szabóné Nagy Mária M','a_id' => '4','t_id' => '9','p_id' => '30','b_datum' => '2021.01.11'),
    array('d_nev' => 'Varga János M','a_id' => '4','t_id' => '3','p_id' => '51','b_datum' => '2021.01.11'),
    array('d_nev' => 'Stromayer Lajos W','a_id' => '4','t_id' => '8','p_id' => '18','b_datum' => '2021.01.11'),
    array('d_nev' => 'Schüszler Edit W','a_id' => '4','t_id' => '8','p_id' => '18','b_datum' => '2021.01.11'),
    array('d_nev' => 'Barkóczi Dániel T','a_id' => '6','t_id' => '7','p_id' => '365','b_datum' => '2021.01.11'),
    array('d_nev' => 'Pécsi Viktória T','a_id' => '4','t_id' => '9','p_id' => '30','b_datum' => '2021.01.11'),
    array('d_nev' => 'Révhegyi Viktor W','a_id' => '4','t_id' => '4','p_id' => '54','b_datum' => '2021.01.11'),
    array('d_nev' => 'Tóth Erika ML','a_id' => '6','t_id' => '8','p_id' => '18','b_datum' => '2021.01.18'),
    array('d_nev' => 'Balogh József ML','a_id' => '6','t_id' => '4','p_id' => '55','b_datum' => '2021.01.18'),
    array('d_nev' => 'Chisalita Ionut ML','a_id' => '6','t_id' => '3','p_id' => '51','b_datum' => '2021.01.18'),
    array('d_nev' => 'Czifra Katalin ML','a_id' => '6','t_id' => '7','p_id' => '353','b_datum' => '2021.01.18'),
    array('d_nev' => 'Csányiné Pál Csilla ML','a_id' => '6','t_id' => '7','p_id' => '353','b_datum' => '2021.01.18'),
    array('d_nev' => 'Csorba Rudolf ML','a_id' => '6','t_id' => '3','p_id' => '51','b_datum' => '2021.01.18'),
    array('d_nev' => 'Csorba Szilvia ML','a_id' => '6','t_id' => '7','p_id' => '361','b_datum' => '2021.01.18'),
    array('d_nev' => 'Hódosné Nagy Anikó ML','a_id' => '6','t_id' => '9','p_id' => '30','b_datum' => '2021.01.18'),
    array('d_nev' => 'Ordas Mihály ','a_id' => '5','t_id' => '4','p_id' => '54','b_datum' => '2021.01.18'),
    array('d_nev' => 'Szedlacsekné Kancsár Katalin ','a_id' => '5','t_id' => '6','p_id' => '5','b_datum' => '2021.01.18'),
    array('d_nev' => 'Lakatos Dániel','a_id' => '5','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Gáspár Zoltánné ','a_id' => '5','t_id' => '7','p_id' => '356','b_datum' => '2021.01.18'),
    array('d_nev' => 'Oláh Szilvia ','a_id' => '5','t_id' => '8','p_id' => '18','b_datum' => '2021.01.18'),
    array('d_nev' => 'Kiss Istvánné ','a_id' => '5','t_id' => '7','p_id' => '361','b_datum' => '2021.01.18'),
    array('d_nev' => 'Oravecz Máté ','a_id' => '5','t_id' => '6','p_id' => '6','b_datum' => '2021.01.18'),
    array('d_nev' => 'Stemler Róbertné ','a_id' => '5','t_id' => '7','p_id' => '361','b_datum' => '2021.01.18'),
    array('d_nev' => 'Stemler Róbert ','a_id' => '5','t_id' => '4','p_id' => '54','b_datum' => '2021.01.18'),
    array('d_nev' => 'Salamon Adorján ','a_id' => '5','t_id' => '7','p_id' => '367','b_datum' => '2021.01.18'),
    array('d_nev' => 'Balogh Dániel','a_id' => '5','t_id' => '3','p_id' => '47','b_datum' => '2021.01.18'),
    array('d_nev' => 'Szász Zsolt Levente ','a_id' => '5','t_id' => '6','p_id' => '49','b_datum' => '2021.01.18'),
    array('d_nev' => 'Mendi Mercédesz ','a_id' => '5','t_id' => '7','p_id' => '356','b_datum' => '2021.01.18'),
    array('d_nev' => 'Horváth Melinda ','a_id' => '5','t_id' => '7','p_id' => '355','b_datum' => '2021.01.18'),
    array('d_nev' => 'Lakatos Mátyás ','a_id' => '5','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Holdosi Viktória ML','a_id' => '6','t_id' => '7','p_id' => '356','b_datum' => '2021.01.18'),
    array('d_nev' => 'Jakab Olga ML','a_id' => '6','t_id' => '8','p_id' => '18','b_datum' => '2021.01.18'),
    array('d_nev' => 'Karvai László ML','a_id' => '6','t_id' => '4','p_id' => '57','b_datum' => '2021.01.18'),
    array('d_nev' => 'Kis Krisztián ML','a_id' => '6','t_id' => '3','p_id' => '47','b_datum' => '2021.01.18'),
    array('d_nev' => 'Kolompár Péterné ML','a_id' => '6','t_id' => '7','p_id' => '355','b_datum' => '2021.01.18'),
    array('d_nev' => 'Kovács Julianna ML','a_id' => '6','t_id' => '7','p_id' => '371','b_datum' => '2021.01.18'),
    array('d_nev' => 'Nagy Szilvia ML','a_id' => '6','t_id' => '9','p_id' => '30','b_datum' => '2021.01.18'),
    array('d_nev' => 'Opoczik Lóránd ML','a_id' => '6','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Orsós Zoltán ML','a_id' => '6','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Petrik Dániel ML','a_id' => '6','t_id' => '7','p_id' => '360','b_datum' => '2021.01.18'),
    array('d_nev' => 'Raffael Márk ML','a_id' => '6','t_id' => '7','p_id' => '368','b_datum' => '2021.01.18'),
    array('d_nev' => 'Rupa György ML','a_id' => '6','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Tóth István ML','a_id' => '6','t_id' => '7','p_id' => '367','b_datum' => '2021.01.18'),
    array('d_nev' => 'Tóth Virág ML','a_id' => '6','t_id' => '7','p_id' => '380','b_datum' => '2021.01.18'),
    array('d_nev' => 'Újvári János ML','a_id' => '6','t_id' => '3','p_id' => '50','b_datum' => '2021.01.18'),
    array('d_nev' => 'Maczkó Kristofer T','a_id' => '6','t_id' => '9','p_id' => '29','b_datum' => '2021.01.18'),
    array('d_nev' => 'Makula Henrietta M','a_id' => '6','t_id' => '9','p_id' => '30','b_datum' => '2021.01.18'),
    array('d_nev' => 'Bereczkiné Farkas Mária M','a_id' => '6','t_id' => '7','p_id' => '355','b_datum' => '2021.01.18'),
    array('d_nev' => 'Nagy Viktória Zsanett M','a_id' => '6','t_id' => '7','p_id' => '353','b_datum' => '2021.01.18'),
    array('d_nev' => 'Kovács József M','a_id' => '6','t_id' => '7','p_id' => '365','b_datum' => '2021.01.18'),
    array('d_nev' => 'Ajtai Andor M','a_id' => '6','t_id' => '7','p_id' => '368','b_datum' => '2021.01.18'),
    array('d_nev' => 'Szabó Árpád M','a_id' => '6','t_id' => '7','p_id' => '374','b_datum' => '2021.01.18'),
    array('d_nev' => 'Ajtai Amanda M','a_id' => '6','t_id' => '7','p_id' => '356','b_datum' => '2021.01.18'),
    array('d_nev' => 'Virányi Tünde ','a_id' => '1','t_id' => '7','p_id' => '356','b_datum' => '2021.1.15'),
    array('d_nev' => 'Lisziné Szőke Melinda ','a_id' => '1','t_id' => '7','p_id' => '380','b_datum' => '2021.1.15'),
    array('d_nev' => 'Kovács Katalin ','a_id' => '1','t_id' => '8','p_id' => '18','b_datum' => '2021.1.15'),
    array('d_nev' => 'Borsányi Roland Attila ','a_id' => '1','t_id' => '8','p_id' => '23','b_datum' => '2021.1.15')
  );
//   foreach ($dolgozok as $dolgozo){
//     echo $dolgozo["d_nev"];
//   }
  


foreach ($dolgozok as $value) {
    if (substr($value["d_nev"], -2) == "ML" || substr($value["d_nev"], -2) == " M" || substr($value["d_nev"], -2) == " T" || substr($value["d_nev"], -2) == " W") {
        //echo "  ".substr($value["d_nev"],0, -2 );
        array_push($newDolgozok, substr($value["d_nev"], 0, -2));
    } else {
        array_push($newDolgozok, $value["d_nev"]);
    }
}
foreach ($newDolgozok as $i) {
    echo $i . '<br>';
}
